config/routes.rb
Pathfinder::Application.routes.draw do
  
  devise_for :users, :controllers => { :confirmations => "confirmations", :omniauth_callbacks => "users/omniauth_callbacks" }
  
  devise_scope :user do
    put "/confirm" => "confirmations#confirm"
  end
  
  resources :users, :only => :show
  resources :trips
  resources :trip_types

  root :to => "static_pages#home"
  
  

end

app/models/trip.rb
class Trip < ActiveRecord::Base
  attr_accessible :name, :trip_type_id, :user_id
  
  belongs_to :user
  belongs_to :trip_type
  
end

app/models/trip_type.rb
class TripType < ActiveRecord::Base
  attr_accessible :description, :name
  
  has_many :trips
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable, :token_authenticatable, :omniauth_providers => [:facebook, :twitter]

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :username, :password, :password_confirmation, :remember_me, :provider, :uid, :first_name, :last_name, :facebook_url 
  # attr_accessible :title, :body
  
  validates :email, presence: true, uniqueness: true
  
  has_many :trips
  
  
  public
  
  def password_required?
    super if confirmed?
  end
  
  def password_match?
    self.errors[:password] << "is needed to sign up" if password.blank?
    self.errors[:password_confirmation] << "is needed to sign up" if password_confirmation.blank?
    self.errors[:password_confirmation] << "doesn't match the original password" if password != password_confirmation
    password == password_confirmation && !password.blank?
  end
  
  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    unless user
      # TO-DO: Change to .new and add skip_confirmation_notice! once new Devise version is released.
      user = User.create(first_name: auth.info.first_name,
      						last_name: auth.info.last_name,
      						email: auth.info.email,
      						provider: auth.provider,
      						uid: auth.uid,
      						facebook_url: auth.extra.raw_info.link
      						)
      # user.skip_confirmation_notice!
      # user.save
    end
    user
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  def facebook_sign_in_and_redirect(resource_or_scope, *args)
    options  = args.extract_options!
    scope    = Devise::Mapping.find_scope!(resource_or_scope)
    resource = args.last || resource_or_scope
    sign_in(scope, resource, options)
    redirect_to confirmation_url(resource, :confirmation_token => resource.confirmation_token)
  end
  
end

app/controllers/confirmations_controller.rb
class ConfirmationsController < Devise::ConfirmationsController

  def show
    self.resource = resource_class.find_by_confirmation_token(params[:confirmation_token]) if params[:confirmation_token].present?
    super if resource.nil? or resource.confirmed?
  end
  
  def confirm
    self.resource = resource_class.find_by_confirmation_token(params[resource_name][:confirmation_token]) if params[resource_name][:confirmation_token].present?
    if resource.update_attributes(params[resource_name].except(:confirmation_token)) && resource.password_match?
      self.resource = resource_class.confirm_by_token(params[resource_name][:confirmation_token])
      set_flash_message :notice, :confirmed
      sign_in_and_redirect(resource_name, resource)
    else
      render :action => "show"
    end
  end

end
  

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController



end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController

  def index
    @trips = Trip.all
  end
  
  def show
    @trip = Trip.find(params[:id])
  end
  
  def new
    @trip = Trip.new
  end
  
  def create
    @trip = Trip.create(params[:trip])
    
    redirect_to @trip
  end
  

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    # find_for_facebook_oauth is defined in User model
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)
    
    if @user.persisted?
      # temporarily trying new facebook_sign_in_and_redirect method to redirect to confirmation page
      facebook_sign_in_and_redirect @user, :event => :authentication #thrown if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def resource_name
    :user
  end
  
  def resource
    @resource ||= User.new
  end
  
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pathfinder</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="container">

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= yield %>

</div>
</body>
</html>

app/views/static_pages/home.html.erb
<div id="registration_module">
<% unless current_user %>
  <h1>Sign up for Pathfinder</h1>
  <h4>Enter your email below and we'll begin setting up your account.</h4>

  <%= form_for(resource, :as => resource_name, :url => user_registration_path(resource)) do |f| %>
    <%= devise_error_messages! %>

    
      <%= f.text_field :email, :placeholder => "username@example.com", :input_html => {:auto_focus => true} %>


      <%= f.submit :value => "I'm in, let's go.", :id => "registration_button" %>
      
      <p>Or <%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %></p>

  <% end %>
  
  <p>Already a member? Sign in below.</p>
  
  <%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
    <%= f.label :email %>
    <%= f.email_field :email %>
    <br>

    <%= f.label :password %>
    <%= f.password_field :password %>
    <br>

    <% if devise_mapping.rememberable? -%>
      <%= f.check_box :remember_me %> <%= f.label :remember_me %>
    <% end -%>

    <%= f.submit "Sign in" %>
  <% end %> 
  
<% else %>
  <h2>Here is some other text for signed in users</h2>
  <p><%= link_to "Browse Trips", trips_path %></p>
  <p><%= link_to "Create a Trip", new_trip_path%></p>
  <p><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></p>
<% end %>
</div>

app/views/trips/index.html.erb
<h1>All trips</h1>

<% @trips.each do |t| %>
  <%= link_to t.name, t %> (<%= t.trip_type.name %>)
  </br>
<% end %>

app/views/trips/new.html.erb
<% if current_user %>
  <h1>Create a new trip</h1>

  <%= form_for(@trip) do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name %>
    
    <%= collection_select(:trip, :trip_type_id, TripType.all, :id, :name, :prompt => "Select a trip type" ) %>
  
    <%= f.hidden_field :user_id, value: current_user.id %>
  
    <%= f.submit %>

  <% end %>

<% else %>  
  <p>You must be registered and signed in to create a trip. <%= link_to "Register here.", root_path %></p>
<% end %>

app/views/trips/show.html.erb
<h1><%= @trip.name %></h1>
<% unless @trip.trip_type.nil? %>
  <%= @trip.trip_type.name %>
<% end %>
<p>Created by <%= link_to @trip.user.username, @trip.user %></p>

app/views/users/show.html.erb
<h3>This profile belongs to <%= @user.username %> </h3>
<p>Justin joined Pathfinder in <%= @user.confirmed_at.strftime("%B %Y") %>